loop_times: 15
timeout_threshold: 1
loop_times_customer_search: 30
timeout_threshold_customer_search: 1
authentication_load: 10
loop_times_override: 10
timeout_threshold_override: 1
standard_retry: 3

first_name: "Automated"
last_name: "Test"
business_name: "Automated Test Business"
address_line_1: "64a London Road"
city: "London"
county: "London"
postcode: "SM4 5BE"
mobile: "07878787878"
landline: "02087878787"
email: "asdf@asdf.com"